export enum Role {
  ADMIN = 'ADMIN',
  ADMIN_AKADEMIK = 'ADMIN_AKADEMIK',
  SEKRETARIAT = 'SEKRETARIAT',
  KAPRODI = 'KAPRODI',
  DOSEN_REGULER = 'DOSEN_REGULER',
  DOSEN_PEMBIMBING = 'DOSEN_PEMBIMBING',
  DOSEN_PENGUJI = 'DOSEN_PENGUJI',
  STAF_PRODI = 'STAF_PRODI',
  MAHASISWA = 'MAHASISWA',
  PUBLIC = 'PUBLIC',
}