export enum StatusSkripsi {
  PENGAJUAN_TOPIK = 'PENGAJUAN_TOPIK',
  BIMBINGAN = 'BIMBINGAN',
  SEMINAR_PROPOSAL = 'SEMINAR_PROPOSAL',
  SIDANG_KOMPREHENSIF = 'SIDANG_KOMPREHENSIF',
  SIDANG_SKRIPSI = 'SIDANG_SKRIPSI',
  REVISI = 'REVISI',
  LULUS = 'LULUS',
  DITOLAK = 'DITOLAK',
}